# Домашняя работа №1. Выполнил Косолапов Андрей Павлович

In [1]:
!pip install numpy jupyter
import numpy as np

### Примеры создания массивов:

In [ ]:
arr = np.array([1, 2, 3, 4]) # Создание массива
print(arr)

[1 2 3 4]


In [5]:
# Этот же массив можно получить используя np.arange()
arr = np.arange(1, 5)
print(arr)

[1 2 3 4]


In [ ]:
arr = np.zeros(3) # Создание массива из нулей
arr

array([0., 0., 0.])

In [ ]:
arr = np.ones(4) # Создание массива из единичек
arr

array([1., 1., 1., 1.])

In [ ]:
arr = np.eye(4) # Создание единичной матрицы размером 4
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((3, 3)) # Создание пустого массива (т.е. заполненного мусором из памяти)

array([[ 6.17779239e-31, -1.23555848e-30,  3.08889620e-31],
       [-1.23555848e-30,  2.68733969e-30, -8.34001973e-31],
       [ 3.08889620e-31, -8.34001973e-31,  4.78778910e-31]])

### Демонстрация атрибутов

In [ ]:
arr = np.random.sample((3, 5)) # Рандомное заполнение массива
arr.shape # Выводим размерность массива

(3, 5)

In [34]:
arr.dtype # Выводим тип массива

dtype('int64')

In [ ]:
arr.ndim # Количество осей массива

2

### Примеры индексирования и срезов

In [ ]:
# Создаем двумерный массивчик для теста :3
arr = np.arange(1, 26).reshape((5, 5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
# Получение одного элемента
arr[1][4]

10

In [24]:
# Получение второго столбца, используя срезы
arr[:,1]

array([ 2,  7, 12, 17, 22])

In [26]:
# Вывод строк в обратном порядке
arr[::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### Примеры векторных операций и базовых статистик

In [27]:
a = np.array([3, 4, 5, 6])
a

array([3, 4, 5, 6])

In [ ]:
# Создание массива из одного числа (такого не было на семинаре, я сам нашёл в интернете)
b = np.full(4, 2) # 4 - shape, 2 - число, которым заполниться массив
b

array([2, 2, 2, 2])

In [ ]:
a * b # Поэлементное умножение

array([ 6,  8, 10, 12])

In [ ]:
b * 2 # Умножение массива на скаляр

array([4, 4, 4, 4])

In [ ]:
b = np.array([10, 20, 30, 40])
a / b # Поэлементное деление

array([0.3       , 0.2       , 0.16666667, 0.15      ])

In [ ]:
a + b # Поэлементное сложение

array([13, 24, 35, 46])

In [41]:
# Демонстрация средней величины (mean) и разных других штук
demo_array = np.array([10, 20, 30, 40, 50])
print('Средняя величина:', demo_array.mean())
print('Минимальный элемент:', demo_array.min())
print('Максимальный элемент:', demo_array.max())

# Нормы (По сути мы определяем каждое значение на отрезке от 0 до 1)
norm = (demo_array - demo_array.min()) / (demo_array.max() - demo_array.min())
print('Нормы:', norm)

Средняя величина: 30.0
Минимальный элемент: 10
Максимальный элемент: 50
Нормы: [0.   0.25 0.5  0.75 1.  ]
